services:

  postgres:
    image: postgres:latest
    container_name: monorepo-secure-demo_pg
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - monorepo-secure-demo_pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: monorepo-secure-demo_backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '3000:3000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: frontend
    container_name: monorepo-secure-demo_frontend
    restart: unless-stopped
    ports:
      - '8081:443'

volumes:
  monorepo-secure-demo_pg_data:

networks:
  default:
    name: monorepo-secure-demo_network