services:

  postgres:
    image: postgres:latest
    container_name: monorepo-secure-demo_pg
    restart: unless-stopped
    env_file:
      - ./apps/backend/.env
    ports:
      - '5432:5432'
    volumes:
      - monorepo-secure-demo_pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: monorepo-secure-demo_backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./apps/backend/.env
    ports:
      - '3000:3000'

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    container_name: monorepo-secure-demo_frontend
    env_file:
      - ./apps/frontend/.env
    restart: unless-stopped
    ports:
      - '8081:443'

volumes:
  monorepo-secure-demo_pg_data:

networks:
  default:
    name: monorepo-secure-demo_network